package org.apache.jsp.view.admin.aluno;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class listaAlunos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Header. Main part -->\r\n");
      out.write("<div id=\"header-main\">\r\n");
      out.write("\t<div class=\"container_12\">\r\n");
      out.write("\t\t<div class=\"grid_12\">\r\n");
      out.write("\t\t\t<div id=\"logo\">\r\n");
      out.write("\t\t\t\t<div id=\"logo_top\">\r\n");
      out.write("\t\t\t\t\t<ul id=\"nav\">\r\n");
      out.write("\t\t\t\t\t\t<li id=\"current\"><a href=\"\">Painel de Controle</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\">Outro</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"logo_bottom\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- End. #Logo -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- End. .grid_12-->\r\n");
      out.write("\t\t<div style=\"clear: both;\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- End. .container_12 -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- End #header-main -->\r\n");
      out.write("<div style=\"clear: both;\"></div>\r\n");
      out.write("<!-- Sub navigation -->\r\n");
      out.write("<div id=\"subnav\">\r\n");
      out.write("\t<div class=\"container_12\">\r\n");
      out.write("\t\t<div class=\"grid_12\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">Alunos</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">Professores</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">Secret&aacute;ria</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">Modadidades</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">Turmas</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- End. .grid_12-->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- End. .container_12 -->\r\n");
      out.write("\t<div style=\"clear: both;\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- End #subnav -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- End #header -->\r\n");
      out.write("<div class=\"container_12\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"grid_12\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"bottom-spacing\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Button -->\r\n");
      out.write("\t\t\t<div class=\"float-right\">\r\n");
      out.write("\t\t\t\t<a href=\"\" class=\"button\"> <span>Novo(a) Aluno(a)<img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../../images/plus-small.gif\"\r\n");
      out.write("\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/plus-small.gif\"\r\n");
      out.write("\t\t\t\t\t\twidth=\"12\" height=\"9\" alt=\"New article\" /></span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Table records filtering -->\r\n");
      out.write("\t\t\tFilter: <select class=\"input-short\">\r\n");
      out.write("\t\t\t\t<option value=\"1\" selected=\"selected\">Select filter</option>\r\n");
      out.write("\t\t\t\t<option value=\"2\">Created last week</option>\r\n");
      out.write("\t\t\t\t<option value=\"3\">Created last month</option>\r\n");
      out.write("\t\t\t\t<option value=\"4\">Edited last week</option>\r\n");
      out.write("\t\t\t\t<option value=\"5\">Edited last month</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Example table -->\r\n");
      out.write("\t\t<div class=\"module\">\r\n");
      out.write("\t\t\t<h2>\r\n");
      out.write("\t\t\t\t<span>Tabela de Alunos(as)</span>\r\n");
      out.write("\t\t\t</h2>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"module-table-body\">\r\n");
      out.write("\t\t\t\t<form action=\"\">\r\n");
      out.write("\t\t\t\t\t<table id=\"myTable\" class=\"tablesorter\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th style=\"width: 5%\">#</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th style=\"width: 20%\">Title</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th style=\"width: 21%\">Author</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th style=\"width: 13%\">Category</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th style=\"width: 13%\">Pages</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th style=\"width: 13%\">Price</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th style=\"width: 15%\"></th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"align-center\">1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href=\"\">Don Quixote</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Cervantes</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>adventure</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>992</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>$11.55</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" /> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/tick-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/tick-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"published\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"edit\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"comments\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"delete\" /></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"align-center\">2</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href=\"\">Lord Jim</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Joseph Conrad</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>thriller</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>400</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>$6.95</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" /> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/minus-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/minus-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"not published\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"edit\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"comments\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"delete\" /></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"align-center\">3</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href=\"\">Inferno</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Dante</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>drama</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>528</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>$8.76</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" /> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/minus-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/minus-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"not published\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"edit\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"comments\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"delete\" /></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"align-center\">4</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href=\"\">David Copperfield</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Charles Dickens</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>literary</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>1024</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>$9.00</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" /> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/tick-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/tick-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"published\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"edit\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"comments\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"delete\" /></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"align-center\">5</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href=\"\">Crime and Punishment</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Fyodor Dostoevsky</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>world literature</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>592</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>$10.85</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" /> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/tick-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/tick-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"published\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"edit\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"comments\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"delete\" /></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"align-center\">6</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href=\"\">Faust</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Johann Wolfgang von Goethe</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>drama</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>464</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>$5.95</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" /> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/tick-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/tick-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"published\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"edit\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"comments\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"delete\" /></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"align-center\">7</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href=\"\">Lord of the Flies</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>William Golding</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>drama</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>190</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>$15.88</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" /> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/minus-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/minus-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"not published\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"edit\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"comments\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"delete\" /></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"align-center\">8</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href=\"\">A Farewell To Arms</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Ernest Hemingway</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>romance</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>304</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>$22.80</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" /> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/tick-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/tick-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"published\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"edit\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"comments\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"delete\" /></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"align-center\">9</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href=\"\">The Old Man and the Sea</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Ernest Hemingway</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>adventure</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>112</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>$4.63</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" /> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/minus-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/minus-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"not published\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"edit\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"comments\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"delete\" /></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"align-center\">10</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href=\"\">The Snows of Kilimanjaro</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Ernest Hemingway</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>adventure</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>144</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>$19.00</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" /> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/tick-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/tick-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"published\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"edit\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"comments\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"delete\" /></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"align-center\">11</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href=\"\">The Sun Also Rises</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Ernest Hemingway</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>drama</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>256</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>$10.20</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" /> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/tick-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/tick-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"published\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"edit\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"comments\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"delete\" /></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"align-center\">12</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href=\"\">The Metamorphosis</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Franz Kafka</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>existentialism</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>94</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>$9.95</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" /> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/minus-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/minus-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"not published\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"edit\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"comments\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"delete\" /></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"align-center\">13</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href=\"\">One Flew Over the Cuckoo's Nest</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Ken Kesey</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>thriller</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>288</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>$10.88</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" /> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/tick-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/tick-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"published\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"edit\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"comments\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"delete\" /></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"align-center\">14</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href=\"\">Moby Dick</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Herman Melville</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>world literature</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>464</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>$5.00</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" /> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/minus-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/minus-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"not published\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"edit\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"comments\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"delete\" /></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"align-center\">15</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href=\"\">The Crucible</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Arthur Miller</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>drama</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>176</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>$10.01</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" /> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/tick-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/tick-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"published\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"edit\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"comments\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"delete\" /></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"align-center\">16</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href=\"\">Death of a Salesman</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Arthur Miller</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>drama</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>448</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>$12.24</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" /> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/tick-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/tick-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"published\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"edit\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"comments\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"delete\" /></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"align-center\">17</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href=\"\">Paradise Lost</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>John Milton</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>christianity</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>512</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>$9.24</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" /> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/minus-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/minus-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"published\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"edit\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"comments\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"delete\" /></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"align-center\">18</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href=\"\">Animal Farm</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>George Orwell</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>criticism &amp; theory</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>113</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>$9.85</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" /> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/minus-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/minus-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"published\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"edit\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"comments\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"delete\" /></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"align-center\">19</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href=\"\">Hamlet</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>William Shakespeare</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>tragedy</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>400</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>$5.99</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" /> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/tick-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/tick-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"published\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"edit\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"comments\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"delete\" /></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"align-center\">20</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href=\"\">Julius Caesar</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>William Shakespeare</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>politics</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>288</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>$5.99</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" /> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/tick-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/tick-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"published\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"edit\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"comments\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"delete\" /></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"align-center\">21</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href=\"\">King Lear</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>William Shakespeare</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>tragedy</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>384</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>$5.99</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" /> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/tick-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/tick-circle.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"published\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/pencil.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"edit\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/balloon.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"comments\" /></a> <a href=\"\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"../../images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/bin.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" alt=\"delete\" /></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<div class=\"pager\" id=\"pager\">\r\n");
      out.write("\t\t\t\t\t<form action=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"first\" src=\"../../images/arrow-stop-180.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/arrow-stop-180.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"first\" /> <img class=\"prev\" src=\"../../images/arrow-180.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/arrow-180.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"prev\" /> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"pagedisplay input-short align-center\" /> <img\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"next\" src=\"../../images/arrow.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/arrow.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"next\" /> <img class=\"last\" src=\"../../images/arrow-stop.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/arrow-stop.gif\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"last\" /> <select class=\"pagesize input-short align-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"10\" selected=\"selected\">10</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"20\">20</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"30\">30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"40\">40</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"table-apply\">\r\n");
      out.write("\t\t\t\t\t<form action=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<span>Apply action to selected:</span> <select\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"input-medium\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"1\" selected=\"selected\">Select action</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"2\">Publish</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"3\">Unpublish</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"4\">Delete</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"clear: both\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- End .module-table-body -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- End .module -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"pagination\">\r\n");
      out.write("\t\t\t<a href=\"\" class=\"button\"><span><img\r\n");
      out.write("\t\t\t\t\tsrc=\"../../images/arrow-stop-180-small.gif\"\r\n");
      out.write("\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/arrow-stop-180-small.gif\"\r\n");
      out.write("\t\t\t\t\theight=\"9\" width=\"12\" alt=\"First\" /> First</span></a> <a href=\"\"\r\n");
      out.write("\t\t\t\tclass=\"button\"><span><img\r\n");
      out.write("\t\t\t\t\tsrc=\"../../images/arrow-180-small.gif\"\r\n");
      out.write("\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/arrow-180-small.gif\"\r\n");
      out.write("\t\t\t\t\theight=\"9\" width=\"12\" alt=\"Previous\" /> Prev</span></a>\r\n");
      out.write("\t\t\t<div class=\"numbers\">\r\n");
      out.write("\t\t\t\t<span>Page:</span> <a href=\"\">1</a> <span>|</span> <a href=\"\">2</a>\r\n");
      out.write("\t\t\t\t<span>|</span> <span class=\"current\">3</span> <span>|</span> <a\r\n");
      out.write("\t\t\t\t\thref=\"\">4</a> <span>|</span> <a href=\"\">5</a> <span>|</span> <a\r\n");
      out.write("\t\t\t\t\thref=\"\">6</a> <span>|</span> <a href=\"\">7</a> <span>|</span> <span>...</span>\r\n");
      out.write("\t\t\t\t<span>|</span> <a href=\"\">99</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<a href=\"\" class=\"button\"><span>Next <img\r\n");
      out.write("\t\t\t\t\tsrc=\"../../images/arrow-000-small.gif\"\r\n");
      out.write("\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/arrow-000-small.gif\"\r\n");
      out.write("\t\t\t\t\theight=\"9\" width=\"12\" alt=\"Next\" /></span></a> <a href=\"\" class=\"button last\"><span>Last\r\n");
      out.write("\t\t\t\t\t<img src=\"../../images/arrow-stop-000-small.gif\"\r\n");
      out.write("\t\t\t\t\ttppabs=\"http://www.xooom.pl/work/magicadmin/images/arrow-stop-000-small.gif\"\r\n");
      out.write("\t\t\t\t\theight=\"9\" width=\"12\" alt=\"Last\" />\r\n");
      out.write("\t\t\t</span></a>\r\n");
      out.write("\t\t\t<div style=\"clear: both;\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- End .grid_12 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div style=\"clear: both;\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- End .container_12 -->\r\n");
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(PageContext _jspx_page_context)
          throws Throwable {
    PageContext pageContext = _jspx_page_context;
    JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fimport_005f0.setParent(null);
    // /view/admin/aluno/listaAlunos.jsp(5,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fimport_005f0.setUrl("../../includes/header.jsp");
    int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
      if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fimport_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(PageContext _jspx_page_context)
          throws Throwable {
    PageContext pageContext = _jspx_page_context;
    JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fimport_005f1.setParent(null);
    // /view/admin/aluno/listaAlunos.jsp(628,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fimport_005f1.setUrl("../../includes/footer.jsp");
    int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
      if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fimport_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
    }
    return false;
  }
}
